
CPPFLAGS += -std=c++11

CXXFLAGS += -g -Wall -Wextra

CXX=g++

all: 1 2 3 4 5 6 7

1: 1.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@ 
2: 2.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@ 
3: 3.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@ 
4: 4.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@ 
5: 5.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@ 
6: 6.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@ 
7: 7.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@ 

clean :
	rm -fr *.o 1.exe 2.exe 3.exe 4.exe 5.exe 6.exe 7.exe